from pathlib import Path
import json
from fontTools.ttLib import TTFont
root=Path('/workspace/sites/the-meridian-archive'); d=root/'dist'; a=d/'assets'
for source,name in [('/usr/share/fonts/opentype/urw-base35/NimbusSans-Regular.otf','grotesk'),('/usr/share/fonts/opentype/urw-base35/NimbusSans-Bold.otf','grotesk-bold'),('/usr/share/fonts/opentype/urw-base35/P052-Italic.otf','editorial-italic'),('/usr/share/fonts/opentype/urw-base35/NimbusMonoPS-Regular.otf','mono')]:
 f=TTFont(source);f.flavor='woff';f.save(a/(name+'.woff'))
m=json.loads((root/'.openai/hosting.json').read_text());m['static']={'directory':'dist'};(root/'.openai/hosting.json').write_text(json.dumps(m,indent=2))
# Original vector artwork: the same formal vocabulary, three distinct compositions.
def svg(name,bg,body):
 (a/(name+'.svg')).write_text(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000"><defs><filter id="grain"><feTurbulence type="fractalNoise" baseFrequency=".72" numOctaves="3" stitchTiles="stitch"/><feColorMatrix type="saturate" values="0"/><feComponentTransfer><feFuncA type="linear" slope=".12"/></feComponentTransfer><feBlend in="SourceGraphic" mode="multiply"/></filter><clipPath id="frame"><rect width="800" height="1000"/></clipPath></defs><g clip-path="url(#frame)"><path fill="{bg}" d="M0 0H800V1000H0z"/>{body}<rect width="800" height="1000" opacity=".35" filter="url(#grain)" fill="transparent"/></g></svg>''')
lines=''.join(f'<ellipse cx="400" cy="505" rx="{170+i*16}" ry="{260+i*9}" fill="none" stroke="#252820" stroke-width="1.3" transform="rotate(-28 400 505)"/>' for i in range(15))
svg('meridian','#BA4B32',f'<circle cx="400" cy="500" r="247" fill="#E9E5D8"/>{lines}<path d="M400 0V1000M0 500H800" stroke="#E9E5D8" stroke-width="1"/><path d="M0 500H800V550H0z" fill="#BA4B32"/><circle cx="400" cy="500" r="9" fill="#252820"/>')
steps=''.join(f'<path d="M{100+i*22} 830V{180+i*23}H{700-i*22}V830" fill="none" stroke="#E9E5D8" stroke-width="3"/>' for i in range(12))
svg('cities','#6B7050',f'{steps}<circle cx="400" cy="620" r="116" fill="#C3BCD0"/><path d="M0 830H800" stroke="#E9E5D8"/><path d="M400 0V1000" stroke="#252820" stroke-width="1"/>')
waves=''.join(f'<path d="M-50 {240+i*22} Q200 {20+i*27} 420 {280+i*18} T850 {220+i*29}" fill="none" stroke="#252820" stroke-width="2"/>' for i in range(23))
svg('sea','#C3BCD0',f'<circle cx="580" cy="240" r="150" fill="#BA4B32"/>{waves}<path d="M0 800H800V1000H0z" fill="#252820"/><path d="M85 850H715M85 878H470" stroke="#C3BCD0"/>')
(a/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80"><rect width="80" height="80" fill="#E9E5D8"/><circle cx="40" cy="40" r="30" fill="#BA4B32"/><path d="M40 0V80M0 40H80" stroke="#252820" stroke-width="4"/></svg>')
navitems=[('books.html','Books'),('about.html','The author'),('essays.html','Field notes'),('signup.html','Letters ↗')]
def nav(active):return ''.join(f'<a href="{url}"'+(' aria-current="page"' if url==active else '')+(' class="letter"' if url=='signup.html' else '')+f'>{label}</a>' for url,label in navitems)
def page(file,title,content,description):
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#e9e5d8"><meta name="description" content="{description}"><title>{title} — The Meridian Archive</title><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="preload" href="assets/grotesk.woff" as="font" type="font/woff" crossorigin><link rel="stylesheet" href="assets/style.css"><script src="assets/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><div class="wrap"><header><div class="topline label"><span>Speculative fiction / Mara Vey</span><span>A self-initiated portfolio concept</span></div><div class="masthead"><a class="brand" href="index.html" aria-label="The Meridian Archive home"><span class="mark" aria-hidden="true"></span><span>The Meridian<br>Archive</span></a><nav class="nav" aria-label="Main navigation">{nav(file)}</nav><details class="mobile-nav"><summary>Index +</summary><nav aria-label="Mobile navigation">{nav(file)}<a href="contact.html">Contact</a></nav></details></div></header><main id="main">{content}</main><footer class="footer"><div class="footer-main"><a class="brand" href="index.html"><span class="mark" aria-hidden="true"></span><span>The Meridian<br>Archive</span></a><nav class="footer-links" aria-label="Archive navigation"><a href="books.html">The novels</a><a href="about.html">Mara Vey</a><a href="essays.html">Field notes</a></nav><nav class="footer-links" aria-label="Contact navigation"><a href="signup.html">Letters from elsewhere ↗</a><a href="contact.html">Correspondence ↗</a><a href="design-system.html">Design notes ↗</a></nav></div><div class="footer-bottom label"><span>Imaginary worlds. Human questions.</span><span>Fictional author & works · Concept design by <a href="https://fathiu.com">Mustapha Fathiu ↗</a></span><span>Archive / 001–026</span></div></footer></div></body></html>'''
 (d/file).write_text(html)
def link(url,label):return f'<a class="arrow-link" href="{url}">{label}<span aria-hidden="true">↗</span></a>'
books=[('meridian','The Meridian Engine','2026','A novel / 01','A machine that remembers the future. A woman determined to forget it.','Mara Vey’s first novel follows a cartographer through a city whose streets are being erased by memories that have not happened yet.','At the edge of the salt plain, a city wakes each morning with one fewer street. Its inhabitants call this progress. Cartographer Iona Vale calls it a crime. When a map begins to show tomorrow’s disappearances, she travels beneath the city to find the machine that dreams them into being.','Memory, cartography, time','284'),('cities','Cities Without Shadows','2024','A novel / 02','Seven cities. One sun. No place left to hide.','An expedition into seven sunlit cities, and the quiet rebellion of people learning to make darkness.','For ninety years, the sun has refused to set. Across seven cities, sleep is a civic duty, silence is a controlled substance, and darkness is only a word in old books. Lio, an apprentice glassmaker, discovers a material that casts a shadow. What begins as a workshop experiment becomes a question no government can answer: what is a life without a private place?','Light, freedom, belonging','312'),('sea','A Sea of Borrowed Names','2022','A novel / 03','On this coast, the sea returns everything except what you lost.','A coastal fable about inheritance, language and the stories we carry for other people.','Every winter, the tide deposits names on the shore. Some arrive on scraps of paper. Others are heard in shells. When Nera discovers her mother’s name written on a stone, she leaves the village to find the person now living under it. Her journey crosses a landscape where identity is a debt, and every introduction is a small act of faith.','Language, inheritance, loss','240')]
def cover(b):
 id,title,year,category,*_=b
 return f'<a class="cover {id}" href="book-{id}.html" aria-label="Explore {title}"><img src="assets/{id}.svg" alt="" width="800" height="1000"><div class="cover-type"><span class="label">Mara Vey / {year}</span><strong>{title}</strong><span class="label">The Meridian Archive<br>Speculative fiction</span></div></a>'
def card(b):return f'<article class="book">{cover(b)}<div class="book-meta label"><span>{b[3]}</span><span>{b[2]}</span></div><h3><a href="book-{b[0]}.html">{b[1]}</a></h3><p>{b[4]}</p></article>'
def band():return f'<section class="section newsletter-band"><div><span class="label">An occasional transmission</span><h2>Letters from<br><em>elsewhere.</em></h2></div><div class="band-copy"><p>New writing, unfinished thoughts and fragments from the edge of the map. Sent when there is something worth saying.</p>{link("signup.html","Enter the correspondence")}</div></section>'
rows='''<a class="journal-row" href="essay-maps.html"><span class="label">Field note 01 / Craft</span><h3>A map is a kind<br>of promise.</h3><span class="end label">06.09.26<br>5 min ↗</span></a><a class="journal-row" href="essay-futures.html"><span class="label">Field note 02 / Futures</span><h3>The future used to<br>have a colour.</h3><span class="end label">18.07.26<br>4 min ↗</span></a>'''
page('index.html','Imaginary worlds. Human questions.',f'''<section class="hero"><div class="hero-meta label"><span>The collected worlds of Mara Vey</span><span>Novels / fragments / possible futures</span></div><h1 class="hero-title">Elsewhere is<br><em>closer than</em><br>you think.</h1><div class="hero-bottom"><div class="hero-copy"><p>Stories for the space between what we know and what we cannot yet imagine.</p>{link('books.html','Explore the archive')}<div class="hero-number" aria-hidden="true">01—</div></div><figure class="hero-art" style="margin:0"><img src="assets/meridian.svg" alt="A pale split sun surrounded by intersecting elliptical orbits on a vermilion field" width="800" height="1000"><figcaption class="art-label label"><span>Fig. 01 / The memory of a sun</span><span>Meridian studies, 2026</span></figcaption></figure></div></section><section class="section"><div class="section-head"><span class="label">01 / Selected worlds</span>{link('books.html','The complete catalogue')}</div><div class="book-grid">{''.join(card(b) for b in books)}</div></section><section class="section statement"><span class="label">A note from<br>the author</span><div><blockquote>“I write about impossible places to ask <em>possible questions.</em> About who we become when the world stops being familiar.”</blockquote><div style="margin-top:30px">{link('about.html','Meet Mara Vey')}</div></div></section><section class="section"><div class="section-head"><span class="label">02 / Notes from the margins</span>{link('essays.html','All field notes')}</div>{rows}</section>{band()}''','A fictional speculative-fiction author archive: original geometric art, novels and literary field notes. Self-initiated design concept.')
page('books.html','The novels',f'''<section class="page-heading"><div class="label">Catalogue / 001–003</div><div class="catalogue-head"><h1>Worlds,<br><em>on paper.</em></h1><span class="series-number" aria-hidden="true">03</span></div><div class="intro-grid"><p class="intro">Three novels. Three departures from the familiar. Each one an invitation to lose your bearings.</p><p class="index-note">The works here belong to a fictional author, created as part of The Meridian Archive’s visual identity. Explore each volume for its story, cover and opening passage.</p></div></section><section class="catalogue-grid"><div class="book-grid flat">{''.join(card(b) for b in books)}</div></section>{band()}''','The complete fictional novels of Mara Vey, with original covers and reading samples.')
excerpts=[['The first street disappeared on a Tuesday. Iona remembered this because Tuesday was the day she sharpened her pencils, and because there was no longer a shop from which to buy them.','She stood at the intersection of Bell and Orison and looked at the blank wall where a doorway ought to have been. The wall was old. That was the part she could not forgive. The city had not merely taken the street; it had arranged to have never possessed it.','On her map, the shop remained. A square no larger than her thumbnail, crosshatched in black. She pressed a finger to the paper and felt, absurdly, that she was keeping someone alive.'],['The first shadow was the size of a button. Lio nearly swept it off the workbench with the glass dust.','It lay beneath the new piece, a small dark circle that moved when he moved the glass. He bent close. For the first time in his life, there was a place the sun could not reach.','Outside, the noon bells rang for the fourth time that day. The city had long ago learned that time was something you made together, not something the sky could be trusted to provide.'],['The sea brought her mother’s name back in November. It was written on a stone so smooth that Nera thought, at first, it was a piece of soap.','She carried it to the kitchen, laid it beside the bread, and waited for it to become an ordinary thing. Her grandmother kept kneading. Neither of them looked at the stone.','“There are rules,” her grandmother said at last. “For names that come back.” Outside, the gulls were arguing over something the tide had left behind.']]
for n,b in enumerate(books):
 id,title,year,cat,tag,short,syn,themes,pages=b
 page(f'book-{id}.html',title,f'''<div class="breadcrumbs label"><a href="books.html">The novels</a><span>/ Volume 0{n+1}</span></div><section class="detail-grid"><div>{cover(b)}<p class="small-note">Original cover design / The Meridian Archive</p></div><div class="detail-text"><span class="label">{cat} / {year}</span><h1>{title}</h1><p class="intro serif">{tag}</p><p>{short}</p><div class="facts"><div class="fact"><span class="label">Format</span><span>Novel / {pages} imagined pages</span></div><div class="fact"><span class="label">Territory</span><span>{themes}</span></div><div class="fact"><span class="label">Status</span><span>Fictional portfolio work</span></div></div>{link('#opening','Read the opening')}</div></section><section class="section reading-layout"><aside class="label">01 / The story</aside><div class="prose"><p>{syn}</p><blockquote>“{tag}”</blockquote></div><span class="label">Mara Vey<br>Volume 0{n+1}</span></section><section id="opening" class="reading-layout"><aside class="label">02 / Opening passage<br>Original concept text</aside><div class="prose"><h2 style="margin-top:0">Chapter one.<br><em>{['The missing street','A private darkness','Names that return'][n]}</em></h2>{''.join(f'<p'+(' class="drop"' if i==0 else '')+f'>{p}</p>' for i,p in enumerate(excerpts[n]))}<p class="label">End of sample</p>{link('book-'+books[(n+1)%3][0]+'.html','Next volume: '+books[(n+1)%3][1])}</div></section>{band()}''',short)
page('about.html','Mara Vey',f'''<section class="page-heading"><div class="label">The author / An imagined biography</div><h1>A life spent<br><em>looking sideways.</em></h1></section><section class="author-panel"><figure class="author-art" style="margin:0"><img src="assets/cities.svg" alt="Nested architectural outlines framing a pale lavender sun" width="800" height="1000"><figcaption class="art-label label"><span>A portrait in coordinates</span><span>MV / 01</span></figcaption></figure><div class="author-text"><p class="serif">“The ordinary world is strange enough. You only have to stand a little further away.”</p><p>Mara Vey is the fictional voice behind The Meridian Archive: a writer of speculative novels about memory, language and the places we build to keep ourselves safe.</p><p>In this imagined biography, she grew up near a tidal estuary, studied architecture, and spent several years drawing buildings that were never built. Fiction became another way of drawing them.</p><p>Her worlds are expansive; her questions are intimate. What do we owe the past? Who gets to name a place? What is left of a person when their memories belong to someone else?</p><span class="label">Fictional author / Original editorial concept</span></div></section><section class="section statement about-end"><span class="label">Working principles</span><div><blockquote>Begin with a place.<br>Find the contradiction.<br><em>Follow the human cost.</em></blockquote><div style="margin-top:35px">{link('essays.html','Notes on writing & world-building')}</div></div></section>{band()}''','Meet Mara Vey, the fictional author behind a self-initiated speculative-fiction design concept.')
page('essays.html','Field notes',f'''<section class="page-heading"><div class="label">Notebook / Essays & correspondence</div><h1>From the<br><em>margins.</em></h1><div class="intro-grid"><p class="intro">Thoughts on invented places, the material world, and the small machinery of a story.</p><p class="index-note">A slower corner of the archive. Original essays written in the fictional author’s voice, accompanied by occasional letters from elsewhere.</p></div></section><section class="section">{rows}</section>{band()}''','Original concept essays on maps, speculative futures and the craft of fictional worlds.')
articles=[('maps','A map is a kind of promise.','Craft / Field note 01','06 September 2026','5 min','cities',[
('Every map begins with an omission. Before the coast can become a line, someone must decide which coves are too small to matter. Before a city can become a grid, someone must decide what counts as a street. The finished thing looks factual. The decisions beneath it are anything but.',''),
('I used to draw the maps for my stories before I wrote the stories themselves. It felt like a responsible kind of preparation: settle the rivers, establish the mountain range, work out how long a journey would take. Then the characters could move through a world that already knew its own shape.',''),
('But the interesting stories always began where the map failed. A road ended where it ought to continue. Two villages disagreed about the river between them. A woman remembered a square that the city insisted had never existed. The map became useful only when it stopped being reliable.','The useful mistake'),
('In The Meridian Engine, Iona makes maps as an act of resistance. She draws what is gone. Her work is not a record of the city as it stands, but an argument with the city as it wishes to be remembered. I wanted the reader to feel that a mark on paper could have weight. That it might cost something to erase it.',''),
('A convincing fictional world does not require exhaustive geography. It requires consequences. If there is a mountain, who cannot cross it? If there is a border, whose family does it divide? If a street vanishes overnight, who has to take the long way home?','A world with consequences'),
('These are smaller questions than “How does the world work?” They are also more useful ones. A reader can forgive a blank space on the map. It is harder to forgive a world in which nothing matters to anyone.',''),
('I still draw maps. But now I leave room for a place I have not understood yet. An unfinished edge. A road whose destination is not a name but a question. Somewhere for the story to surprise me.','')]),('futures','The future used to have a colour.','Futures / Field note 02','18 July 2026','4 min','sea',[
('There is a particular orange that belongs to old ideas of tomorrow. Not the orange of a warning light, or a sunset, but the softened colour of a book cover left on a windowsill. It suggests a future that was once urgent and has since had time to fade.',''),
('I collect these covers for their confidence. Their circles, their impossible buildings, their insistence that an unfamiliar shape could explain an unfamiliar world. They offer no photograph as proof. They ask us to make the journey ourselves.',''),
('What interests me is the distance between the promise and the object. The promised future is weightless. The book is heavy. Its paper yellows, its glue fails, and someone has written a shopping list on the last page. Tomorrow has been handled by ordinary people.','Tomorrow, handled'),
('When I imagine a future, I try to give it the same evidence of use. A public terminal with a loose button. A ceremonial building whose roof leaks. A device repaired with a part from a much older device. These details are not there to make the world look charming. They are there to suggest that people have had to live in it.',''),
('A flawless future leaves very little room for a story. A used future carries disagreement in its surfaces. Someone designed this. Someone paid for it. Someone has found a way to make it do something it was never meant to do.','The marks we leave'),
('Perhaps that is why the faded orange keeps drawing me back. It contains two times at once: the time of the promise and the time of its survival. The future becomes interesting when it acquires a past.','')])]
for slug,title,category,date,minutes,art,paras in articles:
 body=''.join((f'<h2>{sub}</h2>' if sub else '')+f'<p'+(' class="drop"' if i==0 else '')+f'>{p}</p>' for i,(p,sub) in enumerate(paras))
 page('essay-'+slug+'.html',title,f'''<div class="breadcrumbs label"><a href="essays.html">Field notes</a><span>/ {category}</span></div><article><header class="page-heading"><div class="label">{date} / {minutes} read</div><h1 class="article-title">{title}</h1></header><figure class="essay-hero" style="margin-inline:0"><img src="assets/{art}.svg" alt="An abstract geometric study accompanying this essay" width="800" height="1000"></figure><div class="section reading-layout"><aside class="label">Written in the voice<br>of Mara Vey<br><br>Original concept essay</aside><div class="prose">{body}<div style="margin-top:40px">{link('essays.html','Return to field notes')}</div></div><span class="label">The Meridian<br>Archive</span></div></article>{band()}''','An original fictional-author essay: '+title)
for signup in [True,False]:
 file='signup.html' if signup else 'contact.html'
 title='Letters from elsewhere' if signup else 'Correspondence'
 fields='''<div class="field"><label for="name">Your name <span class="label">(optional)</span></label><input id="name" name="name" autocomplete="name" placeholder="How should we address you?" maxlength="120"></div><div class="field"><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" placeholder="you@elsewhere.com" required maxlength="254"></div>'''
 if not signup:fields+='''<div class="field"><label for="subject">Subject</label><input id="subject" name="subject" placeholder="What is on your mind?" required maxlength="180"></div><div class="field"><label for="message">Your message</label><textarea id="message" name="message" placeholder="Begin here…" required maxlength="5000"></textarea></div>'''
 fields+='''<label class="consent"><input type="checkbox" required><span>I understand this is a demonstration. My details will not be sent or stored.</span></label>'''
 page(file,title,f'''<section class="page-heading"><div class="label">{'The correspondence / An occasional letter' if signup else 'Contact / An open channel'}</div><h1>{'Letters from<br><em>elsewhere.</em>' if signup else 'A note,<br><em>from you.</em>'}</h1></section><section class="form-layout"><div class="form-intro"><p class="serif">{'Less noise.<br>More possibility.' if signup else 'Every good conversation begins with a little curiosity.'}</p><p>{'Fragments of new writing. Notes on imaginary places. Things found in the real one. An occasional letter, sent when there is something worth sharing.' if signup else 'A place for questions about the imagined books, conversations about the work, or a thought you would like to leave in the margins.'}</p><p class="label">{'Editorial concept: newsletter signup' if signup else 'Editorial concept: author contact'}<br>Forms validate locally. No mailing service or message delivery is connected.</p></div><form data-demo-form="{'newsletter' if signup else 'contact'}">{fields}<button class="submit" type="submit" disabled>{'Preview signup' if signup else 'Preview message'}<span aria-hidden="true">↗</span></button><p class="small-note">Demonstration only · Nothing is transmitted</p><p class="form-result" role="status" tabindex="-1"></p><noscript><p class="no-js">This form preview requires JavaScript. It does not send submissions.</p></noscript></form></section>''','A clearly labelled static form demonstration for The Meridian Archive portfolio concept.')
page('design-system.html','Design notes','''<section class="page-heading"><div class="label">Behind the archive / Identity notes</div><h1>A future,<br><em>in print.</em></h1></section><section class="section reading-layout"><aside class="label">Self-initiated<br>Portfolio concept<br><br>Design & development<br>Mustapha Fathiu</aside><div class="prose"><p>The Meridian Archive is an original visual identity and static website for an invented speculative-fiction author. It is a design study, not commissioned client work. Mara Vey, the novels, their excerpts and the essays are fictional.</p><h2>One system, many worlds.</h2><p>The art direction takes its cues from the printed futures of the 1970s: bold publishing typography, sun-faded colour, industrial geometry and generous editorial space. Split suns, nesting frames and contour lines form a small graphic vocabulary that changes meaning across each book.</p><h2>Typography & colour.</h2><p>Nimbus Sans carries the headlines and reading text. P052 Italic introduces a literary counterpoint. Nimbus Mono supplies the archive’s labels and coordinates. All fonts are hosted locally. Warm paper and near-black anchor the site; vermilion, olive and lavender distinguish its imagined worlds.</p><h2>Space as structure.</h2><p>A twelve-column desktop grid becomes a six-column intermediate layout and a single reading column on small screens. Uneven book positions and offset notes give way to a clear mobile sequence. Thin rules, generous margins and consistent metadata hold the pages together.</p><h2>Built to travel.</h2><p>The website uses semantic HTML, reusable CSS and a small vanilla JavaScript form enhancement. Original SVG artwork scales without a rendering service. Every page works on static hosting. No framework, build runtime, analytics or external asset request is required.</p><h2>Honest interactions.</h2><p>Book samples are original concept text. Signup and contact demonstrate browser validation and a visible local result. They do not send or store personal information. Navigation and reading remain available without JavaScript.</p></div></section>''','The original design system behind The Meridian Archive self-initiated portfolio concept.')
(root/'README.md').write_text('''# The Meridian Archive

Self-initiated visual identity and static website by Mustapha Fathiu. Mara Vey, all books, excerpts and essays are fictional original concept content. This is not client work.

## Run & host

Serve `dist/` with any static web server, for example `python3 -m http.server 8080 --directory dist`. Upload its contents to GitHub Pages, Netlify, Cloudflare Pages or other static hosting. No build is required. Paths are relative and support subdirectory hosting.

## Architecture

Homepage; books catalogue; three book pages; author; field-note index; two full essays; signup; contact; design notes. All pages are fully rendered HTML. `assets/style.css` is the shared design system. `assets/site.js` only enhances two local form demonstrations. `build.py` regenerates the pages and artwork; it requires fontTools and the URW Base35 font paths in this development environment, but is unnecessary for hosting or editing the finished site.

## Visual system

Paper #E9E5D8; ink #252820; vermilion #BA4B32; olive #6B7050; lavender #C3BCD0. Nimbus Sans regular/bold, P052 Italic, Nimbus Mono. Fluid headings; catalogue labels; limited text measures; offset grids; original split-sun, portal and contour SVGs. Breakpoints: 1000px and 700px. Reduced motion, keyboard focus, skip link, semantic navigation and local validation are supported.

## Forms

Demonstration only. No endpoint, storage, subscription or email delivery. Button labels and result messages state this explicitly. To use for a real author, connect an appropriate service, revise privacy/consent language and replace all fictional content.

## Font licensing

Locally bundled WOFF files are conversions of URW Base35 OpenType fonts, licensed under AGPL with the font embedding exception. License text is included in assets/FONT-LICENSE.txt. Original graphics and concept writing are part of this portfolio project.
''')
